baseURL = "https://vague.club/"
languageCode = "fr"
title = "🌊"
theme = "term"
enableRobotsTXT = true
canonifyURLs = false
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  nofooter = true
  footer = '🌊'

[params.social]
  email = "bonjour@vague.club"
  domain = "vague.club"

[params.fathom]
  host = "logs.yannickschutz.com"
  siteID = "CJCRT"
  hostname = "vague.club"

[permalinks]
  posts = "/:slug"
  pages = "/:slug"
